### ISSUE TITLE
误报“刷新课程信息失败”

### ISSUE THREAD

**Issue by Co1lin** [Harry-Chen/Learn-Helper#100]
最近在使用本插件时，每次刷新均会弹出“刷新课程信息失败”的对话框，尝试重新刷新或者更新凭据均无效，而且实际上是登录成功也刷新成功了的（点击离线查看可以正常使用，可以看到更新出来的数据），感觉是误报。

**Comment by jiegec** [comment]
请更新到 4.4.2

**Comment by Co1lin** [comment]
问题已消失，感谢！

**Comment by Harry-Chen** [comment]
并非误报，网络学堂对一部分 API 增加了 CSRF token 校验，因此原来的请求 403 了。4.4.2 解决了这一问题。
