### ISSUE TITLE
 Learn-Helper 失效

### ISSUE THREAD

**Issue by erbanku** [Harry-Chen/Learn-Helper#101]
**Learn-Helper失效，或许跟[近日网络学堂新增了的 xsrf token 鉴权](https://github.com/Trinkle23897/learn2018-autodown/pull/11#:~:text=%E8%BF%91%E6%97%A5%E7%BD%91%E7%BB%9C%E5%AD%A6%E5%A0%82%E6%96%B0%E5%A2%9E%E4%BA%86%20xsrf%20token%20%E9%89%B4%E6%9D%83%EF%BC%8C%E5%AF%BC%E8%87%B4%E5%8E%9F%E6%9C%89%E7%89%88%E6%9C%AC%E5%A4%B1%E6%95%88)有关，需要修复。**

![image](https://user-images.githubusercontent.com/79493862/132991410-1898e175-ec6f-4cca-8a29-72b580af22da.png)

**Comment by jiegec** [comment]
请升级到 4.4.2

**Comment by Harry-Chen** [comment]
请关注 CHANGELOG，4.4.2 已经解决了这一问题。你可以关注 thu-learn-helper 公众号获取最新更新信息。
