### ISSUE TITLE
公告原文页面无法显示、无法提交作业

### ISSUE THREAD

**Issue by LDYang694** [Harry-Chen/Learn-Helper#103]
课程公告的”公告原文“链接点击进去的页面空白，从一侧的课程文件等进去的页面也是空白。
v4.4.2 (build on Harry-XPS at 2021/09/11 10:00:21)
![微信截图_20210914191454](https://user-images.githubusercontent.com/62846124/133248651-fa1342c0-b3d0-4bf2-af83-e0f4ec45dcdd.png)
![微信截图_20210914191519](https://user-images.githubusercontent.com/62846124/133248655-98a6e1e6-0f85-40af-840e-6ef6333a346d.png)

**Comment by Harry-Chen** [comment]
初步判断是链接后没有带 CSRF Token 导致的

**Comment by Harry-Chen** [comment]
此问题较为复杂，公告部分网页并不依赖链接中的 CSRF Token，而是 AJAX 的时候从 `document.cookie` 里面读取并附加到 API 请求的地址后面。现在的问题是，iframe 里面的网页似乎 `document.cookie` 是空的。

**Comment by Harry-Chen** [comment]
相关描述如下：

https://stackoverflow.com/questions/45094712/iframe-not-reading-cookies-in-chrome

**Comment by Harry-Chen** [comment]
根据 [Chromium 文档](https://www.chromium.org/updates/same-site/test-debug#TOC-Testing-Chrome-extensions) 中的说明：

> The `chrome.cookies` API is able to read and set any kind of cookie, including SameSite cookies. However, a web page embedded in an extension page is considered to be in a third party context for the purposes of `document.cookie` (JavaScript) accesses. For content scripts, the behavior of SameSite cookies is exactly the same as if the request were initiated from the page on which the content script is running.

意味着确实框架中的脚本读不到 cookie，所以无法正常发起带 CSRF Token 的请求。

网络学堂的实现太扭曲了，似乎没有好的办法。

**Comment by Harry-Chen** [comment]
此外，侧栏中的提交作业功能也因为类似原因wufashiyongl阿。

**Comment by Harry-Chen** [comment]
在 1c325e2c0d26b58aaa97f35b170bf38568957a3a 和 218baf3e869f9f602db5a3f1bcf07b730259c914 中进行了修复，下一个版本的更新会包含这些内容。

**Comment by Harry-Chen** [comment]
Released in v4.4.3
