### ISSUE TITLE
课程文件同步异常

### ISSUE THREAD

**Issue by LDYang694** [Harry-Chen/Learn-Helper#105]
4.4.3更新后课程文件同步出错
![QQ截图20210915175117](https://user-images.githubusercontent.com/62846124/133412079-17e69deb-10bf-4a74-ae2c-88273beb36dd.png)
更新后 课程新发送的文件不显示
v4.4.3 (build on Harry-XPS at 2021/09/15 15:45:35)

**Comment by Harry-Chen** [comment]
Console 中有任何报错或者警告吗？

**Comment by Harry-Chen** [comment]
抱歉，经过检查，确实是忘记拉文件了。预计今晚或者明天修复发新版。

**Comment by Harry-Chen** [comment]
Released in v4.4.3.2

**Comment by Harry-Chen** [comment]
@LDYang694 烦请协助确认问题是否解决？

**Comment by LDYang694** [comment]
该问题在v4.4.3.2已解决，感谢
