### ISSUE TITLE
建议：添加对于同步作业至Reminders的课程过滤功能

### ISSUE THREAD

**Issue by zhuml19** [Harry-Chen/Learn-Helper#107]
主要针对类似“实验室科研探究”，“物理实验”等动辄会留80+作业的课，添加到Reminders里之后会很乱

**Comment by Harry-Chen** [comment]
请问 Reminders 指什么？你是否要找的是 LearnX？

**Comment by zhuml19** [comment]
sry，已经重新在learnX仓库提issue了
