### ISSUE TITLE
Chrome Extension 升级 v4.4.3.2 版本后登录时显示“登录失败：未知错误”

### ISSUE THREAD

**Issue by elenacliu** [Harry-Chen/Learn-Helper#108]
如题。

![image.png](https://i.loli.net/2021/09/26/hMmYowjvPU7L4zt.png)

**Comment by Harry-Chen** [comment]
烦请提供 console 和 network 面板的输出

**Comment by elenacliu** [comment]
console 的输出：
![image.png](https://i.loli.net/2021/09/26/i8Mr1v9TGINEF6k.png)

network 的输出：
![image.png](https://i.loli.net/2021/09/26/8cLBioFlHWVfdJn.png)

**Comment by Harry-Chen** [comment]
console 中的警告信息不是错误，从网络请求看似乎也没问题。我（以及若干其他同学）目前无法复现这个问题。可否尝试重装一下插件？

**Comment by elenacliu** [comment]
感谢您的深夜回复！我刚刚尝试了以下方法：更换网络环境（切换不同校园网 WiFi，使用手机热点）、重装插件、重启电脑、关掉某冲浪软件，在 Chrome 上均存在此问题。我随之联想到最近使用 Chrome 访问学校的几个主要网站（如info，academic，mails.tsinghua.edu.cn）均存在无法加载等各种问题，于是下载了 Firefox 插件，并成功登录。

**Comment by Harry-Chen** [comment]
也有可能是 Chrome 中有其他插件（比如广告拦截）导致了此问题，不过看起来不是 Learn Helper 的问题。

**Comment by elenacliu** [comment]
upd: 原因已找到。因为之前在 Chrome 中将 *.tsinghua.edu.cn 添加到了“始终无法使用 Cookie 的网站”中，将其移除后就能正藏登录了
