### ISSUE TITLE
作业详情页有关作业附件的几个 feature request

### ISSUE THREAD

**Issue by dramforever** [Harry-Chen/Learn-Helper#109]
- 作业相关的显示，现在只有一个 card 上的小图标可以标志有附件，hover 的时候才能看到文件名，在作业详情也完全没有提到，visiblility 较差。希望可以在作业详情页增加一个作业附件链接
- 作业附件现在在 Learn-Helper  里只能下载不能预览，但是网络学堂中的作业详情里，点击作业附件的文件名可以打开预览。希望可以在 Learn-Helper 的作业详情页增加预览链接和嵌入的预览页面。
  ![Screenshot_20211001_154411](https://user-images.githubusercontent.com/2818072/135585051-4a143ece-60b0-4d9b-b771-30ac663c7e9d.png)

总之就是作业附件能做成课程文件那样就好了……

**Comment by Harry-Chen** [comment]
可以帮我调研一下API🤣

**Comment by Harry-Chen** [comment]
1. 新版中将会修复
2. 我找不到任何课程有可以预览的作业附件，因此新版中不会包含此功能

**Comment by Harry-Chen** [comment]
Fixed in 6b52d6
