### ISSUE TITLE
4.5.0 版本在 Chrome 下导致直接访问 wlxt 出现403

### ISSUE THREAD

**Issue by jiegec** [Harry-Chen/Learn-Helper#110]
现象：启用 Learn Helper 的时候，通过网页访问 wlxt 出现错误：

![image](https://user-images.githubusercontent.com/6127678/140673825-12b29efb-4d83-4763-8860-e3639951ffed.png)

禁用 Learn Helper 插件后恢复。

**Comment by Harry-Chen** [comment]
未能复现，具体步骤和 URL 是？

**Comment by jiegec** [comment]
URL: https://learn.tsinghua.edu.cn/f/wlxt/index/course/student/index

应该是在访问的时候，执行了 inject csrf token.js，然后设置了 document.cookie

**Comment by Harry-Chen** [comment]
依然无法复现，包括 Chrome 95.0.4638.69 (Windows / macOS)，Edge 95.0.1020.44。试试看只启用 Learn Helper？

**Comment by jiegec** [comment]
怀疑是打开链接的时候，csrf token 泄露到了插件外面，写到了 session storage 里面：


![image](https://user-images.githubusercontent.com/6127678/140695371-0dfc9228-a7a4-4c2a-8037-9423c7d14a59.png)

**Comment by Harry-Chen** [comment]
写的的确就是 session storage： https://github.com/Harry-Chen/Learn-Helper/blob/master/src/inject_csrf_token.js#L3-L20
这样用户关闭页面之后就会自动失效

**Comment by jiegec** [comment]
应该是这个 tab 我一直没关，等 csrf token 超时以后就出锅了。。
