### ISSUE TITLE
建议增加黑暗模式

### ISSUE THREAD

**Issue by tianze0926** [Harry-Chen/Learn-Helper#116]
插件的页面受 Chrome 保护，不能用 Dark Reader 等插件进行第三方渲染

**Comment by Harry-Chen** [comment]
有此计划，但我没有精力和能力进行相关改动

**Comment by RenZihou** [comment]
> 插件的页面受 Chrome 保护，不能用 Dark Reader 等插件进行第三方渲染

可以在 chrome://flags 中查找 Auto Dark Mode for Web Contents 选项，开启后类似于 dark reader，但是由于是浏览器的功能，可以适用于插件页面
