### ISSUE TITLE
Chrome Web Store 标记为不安全

### ISSUE THREAD

**Issue by cubele** [Harry-Chen/Learn-Helper#117]
用的是Edge浏览器，在chrome web store下载的插件，今天浏览器提示`已关闭此扩展，因为 Chrome Web Store 已标记其为不安全。`

在Edge商店中仍可以下载使用。

**Comment by Harry-Chen** [comment]
正在修复中

**Comment by Sim233** [comment]
今天发现Chrome浏览器移除了这个插件，但是在“管理扩展程序”位置仍然可以开启。显示违反Chrome网上应用店政策。
![40b32e111a3c2de986a634b84902a69](https://user-images.githubusercontent.com/52943930/177037620-afe15149-a54e-46e9-af9e-3ad9538fd784.png)

**Comment by Harry-Chen** [comment]
已经单独向 Chrome Web Store 提交了 4.5.1.1 版本以解决此问题。

**Comment by Harry-Chen** [comment]
说明发布在 <https://mp.weixin.qq.com/s/amoEiVEudKLzk5uqIWZ9KA>
