### ISSUE TITLE
定时刷新以避免“未登录”问题

### ISSUE THREAD

**Issue by Ethkuil** [Harry-Chen/Learn-Helper#121]
RT。太久未操作后回来，就会显示“未登录”。

Learn Helper 的“手动刷新”功能使得用户可一键继续操作，而且**能保留在之前操作的位置**，很方便。但如果能在连续几分钟未操作时定时调用一次“手动刷新”，可能会更方便！

**Comment by Harry-Chen** [comment]
可以考虑定期调用登录 API，比刷新要好（不影响任何 UI）。

**Comment by Ethkuil** [comment]
我想到有一种可能容易忽略的情况。

浏览器挂着 Learn Helper 的 tab，使用 Windows 的「休眠」关闭了系统。再次启动系统进入 Learn Helper 时，基本都会出现「未登录」，这个我遇到过很多次。

如果只是定时调用登录 API 的话，似乎会漏掉这种情况？因为 Learn Helper 没有一直在运行。

**Comment by Starrah** [comment]
> 我想到有一种可能容易忽略的情况。
> 
> 浏览器挂着 Learn Helper 的 tab，使用 Windows 的「休眠」关闭了系统。再次启动系统进入 Learn Helper 时，基本都会出现「未登录」，这个我遇到过很多次。
> 
> 如果只是定时调用登录 API 的话，似乎会漏掉这种情况？因为 Learn Helper 没有一直在运行。

是否可能可以改成：全局储存上次登录的时间，在所有操作（比如下载课程文件/作业附件、打开提交作业的IFrame的时候），检查保存的上次登录时间，发现超过一定阈值就静默登录后再执行操作？
相当于是一种懒登录的模式

**Comment by Ethkuil** [comment]
> > 我想到有一种可能容易忽略的情况。
> > 浏览器挂着 Learn Helper 的 tab，使用 Windows 的「休眠」关闭了系统。再次启动系统进入 Learn Helper 时，基本都会出现「未登录」，这个我遇到过很多次。
> > 如果只是定时调用登录 API 的话，似乎会漏掉这种情况？因为 Learn Helper 没有一直在运行。
> 
> 是否可能可以改成：全局储存上次登录的时间，在所有操作（比如下载课程文件/作业附件、打开提交作业的IFrame的时候），检查保存的上次登录时间，发现超过一定阈值就静默登录后再执行操作？ 相当于是一种懒登录的模式

我认为可行。

**Comment by Ethkuil** [comment]
或者也可以在捕获到「未登录」问题的时候自动调用“尝试登录”或“手动刷新”？这样的话不需要添加额外的数据。

**Comment by Harry-Chen** [comment]
Fixed by #123
