### ISSUE TITLE
Firefox 4.5.1版本文件下载

### ISSUE THREAD

**Issue by PIcontroller** [Harry-Chen/Learn-Helper#129]
如果在如图的小按钮处下载，得到的文件后缀消失，文件名变为“downloadFile”。
![图片](https://user-images.githubusercontent.com/69424363/222960897-5d307e3d-da48-4088-8f58-da8b924f90b5.png)
而如果在右侧界面里点击文件下载则正常
![图片](https://user-images.githubusercontent.com/69424363/222960978-c939ea1d-59e9-4ee8-addf-4d0a2f8bf1cf.png)

**Comment by Harry-Chen** [comment]
这个问题是 FireFox 一直存在的，我没有找到解决的办法，见 #71 #98
