### ISSUE TITLE
版本4.6.0建议增加手动切换语言功能

### ISSUE THREAD

**Issue by erbanku** [Harry-Chen/Learn-Helper#134]
通过编译发现即将发布的版本`4.6.0`缺乏语言切换功能。若需更改语言，只能通过更改浏览器语言实现，建议增加手动切换语言功能。

**Comment by Harry-Chen** [comment]
目前的语言机制是 WebExtension 自带的，如果要手动切换比较麻烦

**Comment by erbanku** [comment]
由于课程英文名较长没法完整显示，如果手动切换比较难实现的话或许可以考虑一下把课程名称`WRAP`后显示。

**Comment by Harry-Chen** [comment]
@AsakuraMizu

**Comment by erbanku** [comment]
目前显示效果，几乎无法一眼确定具体是哪一门课程。又想到一个解决办法，可以将栏目的宽度改为可变宽度，这样也能解决问题。
![image](https://github.com/Harry-Chen/Learn-Helper/assets/79493862/30548dad-34c8-4b07-85cf-67b17aa1438f)


> 由于课程英文名较长没法完整显示，如果手动切换比较难实现的话或许可以考虑一下把课程名称`WRAP`后显示。

**Comment by Harry-Chen** [comment]
> 目前显示效果，几乎无法一眼确定具体是哪一门课程。又想到一个解决办法，可以将栏目的宽度改为可变宽度，这样也能解决问题。 ![image](https://user-images.githubusercontent.com/79493862/267495803-30548dad-34c8-4b07-85cf-67b17aa1438f.png)
> 
> > 由于课程英文名较长没法完整显示，如果手动切换比较难实现的话或许可以考虑一下把课程名称`WRAP`后显示。

或许可以考虑增加课程名称的语言 override，这个是可以不受浏览器机制影响的。

**Comment by AsakuraMizu** [comment]
> 目前显示效果，几乎无法一眼确定具体是哪一门课程。又想到一个解决办法，可以将栏目的宽度改为可变宽度，这样也能解决问题。 ![image](https://user-images.githubusercontent.com/79493862/267495803-30548dad-34c8-4b07-85cf-67b17aa1438f.png)
> 
> > 由于课程英文名较长没法完整显示，如果手动切换比较难实现的话或许可以考虑一下把课程名称`WRAP`后显示。

~~还可以把字号调小一点~~

**Comment by erbanku** [comment]
> > 目前显示效果，几乎无法一眼确定具体是哪一门课程。又想到一个解决办法，可以将栏目的宽度改为可变宽度，这样也能解决问题。 ![image](https://user-images.githubusercontent.com/79493862/267495803-30548dad-34c8-4b07-85cf-67b17aa1438f.png)
> > 
> > > 由于课程英文名较长没法完整显示，如果手动切换比较难实现的话或许可以考虑一下把课程名称`WRAP`后显示。
> 
> ~~还可以把字号调小一点~~

缩放浏览器窗口也跟着变小🫠，导致还是显示不全🤣。

建议不这么搞🫠

**Comment by erbanku** [comment]
舒服了，赞👍😎

**Comment by AsakuraMizu** [comment]
不过英文课程名显示不全的问题还是没有解决
