### ISSUE TITLE
版本4.6.0 提交作业时点击【提交】按钮无反应

### ISSUE THREAD

**Issue by yuxuan-z19** [Harry-Chen/Learn-Helper#135]

**Comment by AsakuraMizu** [comment]
指的是在内嵌的网络学堂页面“提交”吗？~~听着感觉像是网络学堂的问题~~

能否提供更多信息，例如控制台中输出的错误等  
（我现在没有可提交的作业，无法复现）

**Comment by hotwords123** [comment]
`injectCsrfToken.js:1`
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Either the 'unsafe-inline' keyword, a hash ('sha256-Axi5rjM+iyOz7Kz49zSjjiq1yueNyYD1MtTOU7GefsY='), or a nonce ('nonce-...') is required to enable inline execution. 

`POST https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/student/tjzy?_csrf=`
> Failed to load resource: the server responded with a status of 403 ()

应该是 CSRF 注入失败了

**Comment by AsakuraMizu** [comment]
> `injectCsrfToken.js:1`
> 
> > Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Either the 'unsafe-inline' keyword, a hash ('sha256-Axi5rjM+iyOz7Kz49zSjjiq1yueNyYD1MtTOU7GefsY='), or a nonce ('nonce-...') is required to enable inline execution.
> 
> `POST https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/student/tjzy?_csrf=`
> 
> > Failed to load resource: the server responded with a status of 403 ()
> 
> 应该是 CSRF 注入失败了

看了一下 貌似不是因为 csrf 注入失败导致的问题  
问一下贴的这个 POST 的 url 里 `_csrf=` 后边的参数是直接缺失了还是因为涉及隐私信息剔掉了

**Comment by AsakuraMizu** [comment]
问一下，两位是不是都用的chrome

**Comment by hotwords123** [comment]
> 问一下，两位是不是都用的chrome

是的，Chrome 116.0.5845.188

**Comment by yuxuan-z19** [comment]
> 问一下，两位是不是都用的chrome

我用的是 Edge 116.0.1938.81 以及 Kiwi Browser 112.0.5615.137

**Comment by AsakuraMizu** [comment]
已在 [473af7](https://github.com/AsakuraMizu/Learn-Helper/commit/473af7122f8e3d5f5b0bb662938954a6cdcc4e8b) 中修复，请等待更新
