### ISSUE TITLE
Edge插件商店版本

### ISSUE THREAD

**Issue by Weslie0803** [Harry-Chen/Learn-Helper#136]
目前Edge插件商店中可供下载的版本仍为v4.5.1，Chrome插件商店中版本为v4.6.1，能否将Edge商店中的版本同步更新到最新版以方便Edge插件更新？

**Comment by Harry-Chen** [comment]
Chrome 是 4.6.0，Edge 的还在审核，并不是我没有更新。

**Comment by Harry-Chen** [comment]
4.6.0 的审核已经通过了，正在 Edge 商店发布。

**Comment by Weslie0803** [comment]
😘🥰❤❤
