### ISSUE TITLE
edge插件和release页面尚未更新4.6版本，目前只能通过chrome使用

### ISSUE THREAD

**Issue by InvincibleWyq** [Harry-Chen/Learn-Helper#137]
4.5.1实测已经没法用了
虽然新edge也能装chrome，但因为之前使用edge addon装的，所以没推送更新，今天还是试了半天。
还望全平台尽快同步更新，辛苦你们了！！！谢谢！

**Comment by Harry-Chen** [comment]
Duplicated with #136
