### ISSUE TITLE
4.6.0版本刷新课程信息失败

### ISSUE THREAD

**Issue by huing4257** [Harry-Chen/Learn-Helper#139]
已尝试商店手动更新/用github的release安装/更新chrome/关代理/关闭其他所有插件

<img width="1440" alt="截屏2023-09-19 10 46 09" src="https://github.com/Harry-Chen/Learn-Helper/assets/97958822/b16f5cde-5e7c-4ff8-8c21-89a93343e0fc">

<img width="685" alt="截屏2023-09-19 10 45 31" src="https://github.com/Harry-Chen/Learn-Helper/assets/97958822/73122990-918a-4a9e-aab0-f45c823ff7ba">

**Comment by Harry-Chen** [comment]
[learn-helper-v4.6.0-dev.zip](https://github.com/Harry-Chen/Learn-Helper/files/12655334/learn-helper-v4.6.0-dev.zip)

请尝试此开发版本，并提供：

1. 开发者工具（F12）命令行的错误信息和上下文（特别是出错前的几条日志）
2. Chrome 提供的错误信息

**Comment by huing4257** [comment]
[hjngdmeookhincinhgjffjgjefpokcfd-1695094014393.log](https://github.com/Harry-Chen/Learn-Helper/files/12655544/hjngdmeookhincinhgjffjgjefpokcfd-1695094014393.log)
但是似乎chrome并不能方便地保存完整的日志
Chrome提供的错误信息与之前相同

**Comment by AsakuraMizu** [comment]
定位了一下，感觉像是课程缺失英文课程名，导致lib解析的时候挂掉了

~~应该不会缺失中文课程名吧（？）~~

**Comment by huing4257** [comment]
我明白了，我有一门北大课程，中英文课程名应该都没有

**Comment by AsakuraMizu** [comment]
> 我明白了，我有一门北大课程，中英文课程名应该都没有

那么它在网络学堂上是怎么显示的呢

**Comment by huing4257** [comment]
<img width="1055" alt="截屏2023-09-19 13 00 35" src="https://github.com/Harry-Chen/Learn-Helper/assets/97958822/13b9e8c7-41f1-4d88-9ea9-c16b650b8da6">

**Comment by erbanku** [comment]
同样的问题，加上北大的课程以后就刷新不了了。
![image](https://github.com/Harry-Chen/Learn-Helper/assets/79493862/3be8611d-4f80-46e1-8fd8-c208f2a7bdab)

[另一个网络学堂脚本](https://github.com/Trinkle23897/learn2018-autodown)也出现问题，加了 `--ignore ''` 就好了，北大课程貌似是没有网络学堂课程名的。

**Comment by nvknow** [comment]
同样的问题，有的北大课程有名字但是有的没有
<img width="885" alt="image" src="https://github.com/Harry-Chen/Learn-Helper/assets/56722477/36d3e960-5109-4522-8629-35023c63bca9">

**Comment by AsakuraMizu** [comment]
以上同学能否尝试一下 4.6.1 版本还是否存在此问题？  
（从 artifacts 中下载： https://github.com/Harry-Chen/Learn-Helper/actions/runs/6321924806 ）

**Comment by nvknow** [comment]
> 以上同学能否尝试一下 4.6.1 版本还是否存在此问题？ （从 artifacts 中下载： https://github.com/Harry-Chen/Learn-Helper/actions/runs/6321924806 ）

我这边没问题了

**Comment by huing4257** [comment]
可以了，感谢
