### ISSUE TITLE
[Bug] Fail to submit homework

### ISSUE THREAD

**Issue by Ethkuil** [Harry-Chen/Learn-Helper#144]
点击「提交」按钮后没有反应；先后两节课的不同作业都是如此，我需要手动打开官方的网络学堂才能提交作业。

**Comment by AsakuraMizu** [comment]
请更新到 4.6.1 版本

see #135

**Comment by Harry-Chen** [comment]
Duplicated

**Comment by Ethkuil** [comment]
> 请更新到 4.6.1 版本
> 
> see #135

Learn Helper 提示更新的时候我更新过了。我想也许问题存在尚未解决的可能：

![screenshots](https://github.com/Harry-Chen/Learn-Helper/assets/77615248/a893f33f-0362-489a-9fe6-6b40a22a19d7)

我使用的浏览器是 Brave，基于 Chromium 117.0.5938.88 正式版本64位。

也许值得测试一下在 Chrome 上该问题是否仍然存在。

**Comment by AsakuraMizu** [comment]
> > 请更新到 4.6.1 版本
> > see #135
> 
> Learn Helper 提示更新的时候我更新过了。我想也许问题存在尚未解决的可能：
> 
> ![screenshots](https://user-images.githubusercontent.com/77615248/271840369-a893f33f-0362-489a-9fe6-6b40a22a19d7.gif) [ ![screenshots](https://user-images.githubusercontent.com/77615248/271840369-a893f33f-0362-489a-9fe6-6b40a22a19d7.gif) ](https://user-images.githubusercontent.com/77615248/271840369-a893f33f-0362-489a-9fe6-6b40a22a19d7.gif) [ ](https://user-images.githubusercontent.com/77615248/271840369-a893f33f-0362-489a-9fe6-6b40a22a19d7.gif)
> 
> 我使用的浏览器是 Brave，基于 Chromium 117.0.5938.88 正式版本64位。
> 
> 也许值得测试一下在 Chrome 上该问题是否仍然存在。

无法复现。在 Brave 版本 1.58.135 Chromium: 117.0.5938.140（正式版本）（64 位）上可以正常提交作业

**Comment by Ethkuil** [comment]
> 无法复现。在 Brave 版本 1.58.135 Chromium: 117.0.5938.140（正式版本）（64 位）上可以正常提交作业

不清楚是什么情况。之后交作业时若有更多信息的话我再来反馈吧。

**Comment by Ethkuil** [comment]
虽然不明白为什么，但确实问题依旧……最近几次作业都是交不了的。看了下现在的网络学堂和 Learn Helper 也算是互有优劣，我选择改用官方的网络学堂+TamperMonkey脚本。
