### ISSUE TITLE
[bug] [v4.6.1] 刷新课程信息失败

### ISSUE THREAD

**Issue by Naturean** [Harry-Chen/Learn-Helper#145]
尝试过手动刷新、更新凭据以及重装插件，运行环境：win11、Edge浏览器
事故发生前后课程表稍有变化——网络学堂增加了“形势与政策讨论课”
这与4.6.0版本因为北大课程加入的错误原因很接近，疑似本次错误的发生原因
![image](https://github.com/Harry-Chen/Learn-Helper/assets/112891509/7dee7df8-343c-48ed-8b96-5e6ea98748ee)

**Comment by Harry-Chen** [comment]
是否能提供一些调试信息/日志？

**Comment by Naturean** [comment]
> 是否能提供一些调试信息/日志？

这个是吗？文科生不太懂
![image](https://github.com/Harry-Chen/Learn-Helper/assets/112891509/32b1c09f-637e-47b9-806d-0237e382077b)

**Comment by AsakuraMizu** [comment]
[learn-helper-v4.6.1-dev.zip](https://github.com/Harry-Chen/Learn-Helper/files/12910012/learn-helper-v4.6.1-dev.zip)

> 请尝试此开发版本，并提供：
> 
> 1. 开发者工具（F12）命令行的错误信息和上下文（特别是出错前的几条日志）

**Comment by Naturean** [comment]
> [learn-helper-v4.6.1-dev.zip](https://github.com/Harry-Chen/Learn-Helper/files/12910012/learn-helper-v4.6.1-dev.zip)
> 
> > 请尝试此开发版本，并提供：
> > 
> > 1. 开发者工具（F12）命令行的错误信息和上下文（特别是出错前的几条日志）

开发版本仍然出错，以下是Learn Helper（开发版本）从开始加载到错误出现时F12控制台（Console）的全文信息（对错误信息及部分上下文进行了展开，虽然不知道有没有用）

![image](https://github.com/Harry-Chen/Learn-Helper/assets/112891509/d5f15591-1acf-4882-ba14-4d0fc3011786)
![image](https://github.com/Harry-Chen/Learn-Helper/assets/112891509/feb334a5-c4cd-4f06-967f-db3a6ae3ce19)
![image](https://github.com/Harry-Chen/Learn-Helper/assets/112891509/615f7921-11d4-4fd5-9208-335c8c1510aa)
![image](https://github.com/Harry-Chen/Learn-Helper/assets/112891509/9f19862d-8866-42ae-9f57-2fe7c4419c75)
![image](https://github.com/Harry-Chen/Learn-Helper/assets/112891509/c7e7a484-f684-43af-8ea7-23339f9c8a34)

**Comment by AsakuraMizu** [comment]
如果我没猜错的话应该是网络学堂上没有课程时间导致的

试一下这个能用吗：[learn-helper-v4.6.1-timenlocation.zip](https://github.com/Harry-Chen/Learn-Helper/files/12911775/learn-helper-v4.6.1-timenlocation.zip)

**Comment by Naturean** [comment]
> 如果我没猜错的话应该是网络学堂上没有课程时间导致的
> 
> 试一下这个能用吗：[learn-helper-v4.6.1-timenlocation.zip](https://github.com/Harry-Chen/Learn-Helper/files/12911775/learn-helper-v4.6.1-timenlocation.zip)

成功=v=

**Comment by robertying** [comment]
learnX 也收到很多无法刷新课程的反馈，不知道是不是同一个问题。https://github.com/robertying/learnX/issues/1049

**Comment by AsakuraMizu** [comment]
> learnX 也收到很多无法刷新课程的反馈，不知道是不是同一个问题。[robertying/learnX#1049](https://github.com/robertying/learnX/issues/1049)

大概是的。

https://github.com/robertying/thu-learn-lib-no-native/blob/a93b983d8c3ea29adba6236dbe9e98a5cf46bd97/src/index.ts#L342  
https://github.com/Harry-Chen/thu-learn-lib/blob/80bd9694d9d0f260198f2bf0d9143509967e1312/src/index.ts#L294

给这里加个 try-catch fallback 就可以正常工作了
