### ISSUE TITLE
优化作业页面排序

### ISSUE THREAD

**Issue by HustreLiny** [Harry-Chen/Learn-Helper#148]
希望能把未完成作业排在“所有作业”的最前面
按DDL剩余时间排序导致前面都是已完成的作业，十分迷惑。

**Comment by Harry-Chen** [comment]
根据排序逻辑，的确是这样的：

https://github.com/Harry-Chen/Learn-Helper/blob/fd478be689c4352deb492057e1e9f8e92bc29a2f/src/redux/actions.ts#L334-L348

@AsakuraMizu 看一下为何不符合预期？

**Comment by AsakuraMizu** [comment]
> 根据排序逻辑，的确是这样的：
> 
> https://github.com/Harry-Chen/Learn-Helper/blob/fd478be689c4352deb492057e1e9f8e92bc29a2f/src/redux/actions.ts#L334-L348
> 
> @AsakuraMizu 看一下为何不符合预期？

他的意思是加一个按作业的 `submitted` 排序。祖传下来的排序逻辑并没有考虑这个
