### ISSUE TITLE
[bug report] 部分附件文件预览问题

### ISSUE THREAD

**Issue by fuyh20** [Harry-Chen/Learn-Helper#150]
* 浏览器：egde 版本 118.0.2088.61 (正式版本) (64 位)
* version: 4.6.2
* 文件预览会出现只有第一页的情况

update:
* 网络学堂文件预览也有同样的问题，不是插件的原因

**Comment by AsakuraMizu** [comment]
对是网络学堂更新了pdf viewer的问题，先观望一下
