### ISSUE TITLE
课程文件功能增强

### ISSUE THREAD

**Issue by rouVling** [Harry-Chen/Learn-Helper#157]
![image](https://github.com/Harry-Chen/Learn-Helper/assets/74416460/3f0d0cfe-724f-4602-9748-f4e7b32dbacc)

如上，一部分老师会在课程文件中增加分类，希望插件支持课程文件分类功能

**Comment by Harry-Chen** [comment]
See https://github.com/Harry-Chen/thu-learn-lib/issues/57

**Comment by AsakuraMizu** [comment]
Duplicate of #143
