### ISSUE TITLE
[bug report]课件文件名出错

### ISSUE THREAD

**Issue by Zzzzzzny** [Harry-Chen/Learn-Helper#166]
![image](https://github.com/user-attachments/assets/00acfe0d-2b7d-48bf-a30d-eb2a5bb5a13b)
如图，出现了不知道来自哪里的文件名

**Comment by jiegec** [comment]
直接通过网页版网络学堂，访问课程文件得到的链接是正确的吗？

**Comment by jiegec** [comment]
链接里面有课程的 ID 和文件的 ID，可以比对一下，看看是谁的问题。

**Comment by AsakuraMizu** [comment]
这个页面是网络学堂的，与我们无关
