### ISSUE TITLE
课程名字太长显示超出了边框的范围

### ISSUE THREAD

**Issue by LyricZhao** [Harry-Chen/Learn-Helper#61]
![image](https://user-images.githubusercontent.com/35299455/64489753-4a468980-d289-11e9-9222-f9532562d38c.jpg)

如图所示，在亲密关系那门课中因为名字太长超过了边框范围

**Comment by Harry-Chen** [comment]
zhi'q之前版本中已经改为省略号截断：

![image](https://user-images.githubusercontent.com/2819727/121670418-fca32480-cadf-11eb-912e-63d0de08472a.png)
