### ISSUE TITLE
无法切换到本学期

### ISSUE THREAD

**Issue by function2-llx** [Harry-Chen/Learn-Helper#92]
版本为 4.4.0

如图，选项中无法找到"2020-2021春季学期"。

![image](https://user-images.githubusercontent.com/38486514/111025850-e1157880-8421-11eb-9ec6-cc859a2d9eab.png)

**Comment by Harry-Chen** [comment]
感谢反馈，不过目前我找不到环境复现，有需要可以直接清空数据。

如果还保留着环境，可以查看一下 console 中的 `update_semester_list` 的 action 的数据，是否包含 ·2020-2021-2`，如图（可能需要进行一下手动刷新才能看到这个动作）：

![image](https://user-images.githubusercontent.com/2819727/111026886-d2ca5b00-8427-11eb-9ab1-3dac0abced27.png)

**Comment by function2-llx** [comment]
感谢回复！

如图我查看了对应数据，的确看不见相关内容。不过，如果我选择手动刷新的话，还是会提醒我切换到当前网络学堂的学期（2020-2021 春季学期）。

![图片](https://user-images.githubusercontent.com/38486514/111027084-f346e500-8428-11eb-82b7-1422527f421a.png)

**Comment by Harry-Chen** [comment]
你本学期选课了吗？获取当前学期和获取学期列表是不同的 API，有人似乎报告过后一个不会列出来没选课的学期

**Comment by function2-llx** [comment]
我这学期确实没有选课，只有一门毕设

**Comment by Harry-Chen** [comment]
> 我这学期确实没有选课，只有一门毕设

看来的确是我想的情况了，可以考虑下一个版本做一个特判，把当前学期加进去

**Comment by Harry-Chen** [comment]
目前网络学堂似乎也会给出没有选课的学期了，可以测试一下此问题是否还存在？

**Comment by function2-llx** [comment]
看上去仍然存在：

![图片](https://user-images.githubusercontent.com/38486514/131435507-41017207-b366-4fd9-b1e5-3429538f5bbc.png)

**Comment by Harry-Chen** [comment]
Fixed in https://github.com/Harry-Chen/Learn-Helper/commit/32952ae158deb7c5c9d758884071a9e4b6639c96

https://github.com/Harry-Chen/Learn-Helper/blob/32952ae158deb7c5c9d758884071a9e4b6639c96/src/components/dialogs/ChangeSemesterDialog.tsx#L89-L96

**Comment by Harry-Chen** [comment]
Released in v4.4.1.
