### ISSUE TITLE
Firefox扩展版本中下载文件无法正确获得文件名

### ISSUE THREAD

**Issue by comradez** [Harry-Chen/Learn-Helper#98]
Firefox版本：89.0

Firefox扩展在点击卡片上的“下载文件”时，文件名无法正确获取，而是变成"downloadFile"
![图片](https://user-images.githubusercontent.com/9498051/121649730-70870200-cacb-11eb-87ee-da5634c37cdb.png)
![图片](https://user-images.githubusercontent.com/9498051/121649964-a6c48180-cacb-11eb-8bdd-4fefdc8cfca5.png)
但是单击右侧的下载文件链接，则可以正确地得到文件名，浏览器也可以依据扩展名决定正确的行为
![图片](https://user-images.githubusercontent.com/9498051/121650071-c78cd700-cacb-11eb-9432-71d34b0bde56.png)

**Comment by Harry-Chen** [comment]
duplicate with #71

**Comment by Harry-Chen** [comment]
这个和 #71 略有区别，右侧是 `a` 标签，通过弹出新页面的方式打开：

https://github.com/Harry-Chen/Learn-Helper/blob/ba5515974a24c5b5345e6bff5471edd5bc3e1484/src/components/ContentDetail.tsx#L178-L182

但是由于技术限制，卡片的按钮不能这样，用的是 WebExtension API：

https://github.com/Harry-Chen/Learn-Helper/blob/ba5515974a24c5b5345e6bff5471edd5bc3e1484/src/utils/download.ts#L1-L12

可能是 FireFox 对后者的支持不完整，没有通过 HTTP Header 正确获得文件名。

**Comment by function2-llx** [comment]
Learn Helper 4.4.2 还是有这个问题。

似乎是因为如果调用 `browser.downloads.download` 只提供 url 的话，firefox 会默认把文件名设为 url 中 path 的最后部分，所以其实下载文件的 url 的形式是：`https://learn.tsinghua.edu.cn/b/wlxt/kj/wlkc_kjxxb/student/downloadFile?sfgk=&wjid=`，所以才会默认命名为 `downloadFile`。

然后我试着直接点击控制台中输出的下载 url，则可以正常下载且自动命名。

**Comment by Harry-Chen** [comment]
由于一些技术限制，我无法在左侧的卡片中使用 `<a>` 标签嵌入链接。事实上 WebExtension API 正是由 FireFox 发起的，很奇怪 FF 本身的 `download` 函数不支持 `content-disposition` header 获得正确的文件名。此外使用打开新页面的方式发起下载始终是不可靠的：考虑如果它是一个 PDF/MP4 等浏览器可预览的文件，那么就不会触发正常的下载流程。
